// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrghTDz1rtwzEWlwdCmee9-2GLS4kfzA',
    appId: '1:460020327878:web:5787c4c8a273f798d67ec7',
    messagingSenderId: '460020327878',
    projectId: 'practice-firebase-c9cf4',
    authDomain: 'practice-firebase-c9cf4.firebaseapp.com',
    storageBucket: 'practice-firebase-c9cf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa1cHacVdYrz2zfoO2oF6G2MjFgFDYIYA',
    appId: '1:460020327878:android:fb2f2ef616c5ac3dd67ec7',
    messagingSenderId: '460020327878',
    projectId: 'practice-firebase-c9cf4',
    storageBucket: 'practice-firebase-c9cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsn-qFntucrpBcWjw7A8n6JLuAYjruJs',
    appId: '1:460020327878:ios:5d28dcd95aa3c346d67ec7',
    messagingSenderId: '460020327878',
    projectId: 'practice-firebase-c9cf4',
    storageBucket: 'practice-firebase-c9cf4.firebasestorage.app',
    iosBundleId: 'com.example.practiceFirebase',
  );
}
