// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7j4u9-FI8Sl64LVQ_fASvo1kTgNxeUY',
    appId: '1:161595444791:android:debeeba7fb2fe57214f9b2',
    messagingSenderId: '161595444791',
    projectId: 'to-do-list-thongnt',
    storageBucket: 'to-do-list-thongnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwjhO7RlF904ldQv4rU-knCD3-sneFOA4',
    appId: '1:161595444791:ios:b2e75aaa90a8865314f9b2',
    messagingSenderId: '161595444791',
    projectId: 'to-do-list-thongnt',
    storageBucket: 'to-do-list-thongnt.firebasestorage.app',
    iosBundleId: 'com.example.lesson5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO_67t0PbxXrZWJg4cAy2mDBS__Ba22sg',
    appId: '1:161595444791:web:d189a5071cf6907714f9b2',
    messagingSenderId: '161595444791',
    projectId: 'to-do-list-thongnt',
    authDomain: 'to-do-list-thongnt.firebaseapp.com',
    storageBucket: 'to-do-list-thongnt.firebasestorage.app',
  );

}